# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RandomQuoteProvider.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19RandomQuoteProvider.proto\"\x07\n\x05\x45mpty\"%\n\x05Quote\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t2,\n\x13RandomQuoteProvider\x12\x15\n\x03Get\x12\x06.Empty\x1a\x06.QuoteB\x10\xaa\x02\rQuoteOfTheDayb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RandomQuoteProvider_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\rQuoteOfTheDay'
  _globals['_EMPTY']._serialized_start=29
  _globals['_EMPTY']._serialized_end=36
  _globals['_QUOTE']._serialized_start=38
  _globals['_QUOTE']._serialized_end=75
  _globals['_RANDOMQUOTEPROVIDER']._serialized_start=77
  _globals['_RANDOMQUOTEPROVIDER']._serialized_end=121
# @@protoc_insertion_point(module_scope)
