# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import RandomQuoteProvider_pb2 as RandomQuoteProvider__pb2


class RandomQuoteProviderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/RandomQuoteProvider/Get',
                request_serializer=RandomQuoteProvider__pb2.Empty.SerializeToString,
                response_deserializer=RandomQuoteProvider__pb2.Quote.FromString,
                )


class RandomQuoteProviderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RandomQuoteProviderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=RandomQuoteProvider__pb2.Empty.FromString,
                    response_serializer=RandomQuoteProvider__pb2.Quote.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RandomQuoteProvider', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RandomQuoteProvider(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RandomQuoteProvider/Get',
            RandomQuoteProvider__pb2.Empty.SerializeToString,
            RandomQuoteProvider__pb2.Quote.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
